name: meprofile-backend
region: nyc

services:
  - name: web
    github:
      repo: sh78ba/MeProfiled
      branch: main
      deploy_on_push: true
    source_dir: /backend
    dockerfile_path: backend/Dockerfile
    
    instance_size_slug: basic-xs  # 512MB RAM, $5/month
    # instance_size_slug: basic-s   # 1GB RAM, $12/month (use this if 512MB fails)
    
    instance_count: 1
    
    http_port: 5001
    
    envs:
      - key: FLASK_ENV
        value: production
      - key: MODEL_NAME
        value: distiluse-base-multilingual-cased-v2
      - key: ALLOWED_ORIGINS
        value: https://meprofile-frontend.vercel.app
        
    health_check:
      http_path: /health
      initial_delay_seconds: 60
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
      
    routes:
      - path: /
